import { eq } from "drizzle-orm";
import { z } from "zod";
import { NextRequest, NextResponse } from "next/server";
import { financeBudgets } from "@/db/schema";
import { database } from "@/lib/db";
import { apiError, requireServiceAccess } from "@/lib/api";
const input=z.object({budgetCode:z.string().trim().min(2).max(64),amountZmw:z.coerce.number().positive().max(99999999999999.99),notes:z.string().trim().max(4000).optional()});
export async function PATCH(request:NextRequest){const denied=requireServiceAccess(request,"budgets.manage");if(denied)return denied;const id=request.nextUrl.searchParams.get("id");if(!id)return NextResponse.json({error:"Budget id is required."},{status:400});const parsed=input.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Invalid budget update",details:parsed.error.flatten()},{status:422});try{const[existing]=await database().select({id:financeBudgets.id,status:financeBudgets.status}).from(financeBudgets).where(eq(financeBudgets.id,id)).limit(1);if(!existing)return NextResponse.json({error:"Budget not found."},{status:404});if(existing.status!=="DRAFT")return NextResponse.json({error:"Only DRAFT budgets can be edited."},{status:422});const[updated]=await database().update(financeBudgets).set({...parsed.data,amountZmw:String(parsed.data.amountZmw),updatedAt:new Date()}).where(eq(financeBudgets.id,id)).returning();return NextResponse.json(updated);}catch(error){return apiError(error);}}
export async function DELETE(request:NextRequest){const denied=requireServiceAccess(request,"budgets.manage");if(denied)return denied;const id=request.nextUrl.searchParams.get("id");if(!id)return NextResponse.json({error:"Budget id is required."},{status:400});try{const[existing]=await database().select({id:financeBudgets.id,status:financeBudgets.status}).from(financeBudgets).where(eq(financeBudgets.id,id)).limit(1);if(!existing)return NextResponse.json({error:"Budget not found."},{status:404});if(existing.status!=="DRAFT")return NextResponse.json({error:"Only DRAFT budgets can be deleted."},{status:422});await database().delete(financeBudgets).where(eq(financeBudgets.id,id));return NextResponse.json({ok:true});}catch(error){return apiError(error);}}
