import { eq } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { activities } from "@/db/schema";
import { database } from "@/lib/db";
import { apiError, requireServiceAccess } from "@/lib/api";
import { getRequestSession } from "@/lib/auth";
import { activityInput } from "@/lib/validation";
import { recordAuditEvent } from "@/lib/audit";
export async function PATCH(request:NextRequest,{params}:{params:Promise<{id:string}>}){const denied=requireServiceAccess(request,"activities.manage");if(denied)return denied;const s=getRequestSession(request);if(!s)return NextResponse.json({error:"Authenticated session required."},{status:401});try{const{id}=await params;const p=activityInput.partial().safeParse(await request.json());if(!p.success)return NextResponse.json({error:"Invalid activity",details:p.error.flatten()},{status:422});const[before]=await database().select().from(activities).where(eq(activities.id,id)).limit(1);if(!before)return NextResponse.json({error:"Activity not found."},{status:404});if(before.approvalStatus==="APPROVED"&&p.data.approvalStatus&&p.data.approvalStatus!=="APPROVED")return NextResponse.json({error:"Approved activities must use the governed approval workflow."},{status:409});const[updated]=await database().update(activities).set({...p.data,updatedAt:new Date()}).where(eq(activities.id,id)).returning();await recordAuditEvent({actorUserId:s.userId,action:"ACTIVITY_UPDATED",entityType:"activity",entityId:id,beforeValue:before,afterValue:updated});return NextResponse.json(updated);}catch(e){return apiError(e);}}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{id:string}>}){const denied=requireServiceAccess(request,"activities.manage");if(denied)return denied;const s=getRequestSession(request);if(!s)return NextResponse.json({error:"Authenticated session required."},{status:401});try{const{id}=await params;const[before]=await database().select().from(activities).where(eq(activities.id,id)).limit(1);if(!before)return NextResponse.json({error:"Activity not found."},{status:404});if(before.approvalStatus==="APPROVED")return NextResponse.json({error:"Approved activities cannot be deleted."},{status:409});await database().delete(activities).where(eq(activities.id,id));await recordAuditEvent({actorUserId:s.userId,action:"ACTIVITY_DELETED",entityType:"activity",entityId:id,beforeValue:before});return NextResponse.json({ok:true});}catch(e){return apiError(e);}}
