import Link from "next/link";
import { desc } from "drizzle-orm";
import { managementActions } from "@/db/schema";
import { database } from "@/lib/db";
export const dynamic = "force-dynamic";
function date(value: Date | string | null) { return value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "—"; }
export default async function ManagementPage() {
 const db=database(); const actions=await db.select().from(managementActions).orderBy(desc(managementActions.updatedAt),desc(managementActions.createdAt));
 const open=actions.filter(a=>a.status==="OPEN"), inProgress=actions.filter(a=>a.status==="IN_PROGRESS"), critical=actions.filter(a=>a.severity==="CRITICAL"&&a.status!=="COMPLETED"&&a.status!=="CANCELLED"), today=new Date().toISOString().slice(0,10), overdue=actions.filter(a=>a.dueDate&&a.dueDate<today&&(a.status==="OPEN"||a.status==="IN_PROGRESS"));
 return <main className="page-content" style={{maxWidth:1200,margin:"0 auto",padding:"32px"}}><div className="title-bar"><div><p className="eyebrow">EXECUTIVE MANAGEMENT</p><h1>Management Attention</h1><p>Decisions, actions, ownership and unresolved issues requiring management attention.</p></div><Link className="primary-button" href="/dashboard/finance">Financial intelligence →</Link></div><section className="stats-grid"><article className="metric-card metric-navy"><div className="metric-top"><span>OPEN</span></div><strong>{open.length}</strong><p>Open findings</p><small>Awaiting management resolution</small></article><article className="metric-card metric-blue"><div className="metric-top"><span>IN PROGRESS</span></div><strong>{inProgress.length}</strong><p>Actions underway</p><small>Assigned and being addressed</small></article><article className="metric-card metric-gold"><div className="metric-top"><span>OVERDUE</span></div><strong>{overdue.length}</strong><p>Overdue actions</p><small>Past their recorded due date</small></article><article className="metric-card metric-light"><div className="metric-top"><span>CRITICAL</span></div><strong>{critical.length}</strong><p>Critical unresolved</p><small>Highest management attention</small></article></section><section className="panel" style={{marginTop:24,padding:24}}><div className="panel-heading"><div><p className="eyebrow dark">MANAGEMENT CONTROL</p><h2>Outstanding decisions & actions</h2></div><span className="more">{actions.length} TOTAL</span></div>{actions.length===0?<p>No management findings have been raised.</p>:<div className="activity-table">{actions.slice(0,30).map(a=><article className="activity-row" key={a.id}><div className={`activity-mark ${a.severity==="CRITICAL"?"navy":a.severity==="HIGH"?"blue":"gold"}`}>{a.severity.slice(0,1)}</div><div className="activity-main"><strong>{a.finding}</strong><span>{a.entityType} · {a.source}</span><small>{a.recommendation}</small></div><span className="status blue">{a.status.replaceAll("_"," ")}</span><time>{a.dueDate?`Due ${date(a.dueDate)}`:"No due date"}</time></article>)}</div>}</section><section className="panel" style={{marginTop:24,padding:24}}><div className="panel-heading"><div><p className="eyebrow dark">MANAGEMENT SIGNAL</p><h2>What requires attention</h2></div></div><p>Use Financial Intelligence for the underlying financial and delivery evidence. This view focuses on resulting management decisions and actions.</p></section></main>;
}
