import { eq } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { directorates } from "@/db/schema";
import { database } from "@/lib/db";
import { apiError, requireServiceAccess } from "@/lib/api";
import { getRequestSession } from "@/lib/auth";
import { directorateInput } from "@/lib/validation";
import { recordAuditEvent } from "@/lib/audit";
export async function PATCH(request: NextRequest,{params}:{params:Promise<{id:string}>}){const denied=requireServiceAccess(request,"directorates.manage");if(denied)return denied;const session=getRequestSession(request);if(!session)return NextResponse.json({error:"Authenticated session required."},{status:401});try{const{id}=await params;const parsed=directorateInput.partial().safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Invalid directorate.",details:parsed.error.flatten()},{status:422});const[before]=await database().select().from(directorates).where(eq(directorates.id,id)).limit(1);if(!before)return NextResponse.json({error:"Directorate not found."},{status:404});const[updated]=await database().update(directorates).set({...parsed.data,updatedAt:new Date()}).where(eq(directorates.id,id)).returning();await recordAuditEvent({actorUserId:session.userId,action:"DIRECTORATE_UPDATED",entityType:"directorate",entityId:id,beforeValue:before,afterValue:updated});return NextResponse.json(updated);}catch(error){return apiError(error);}}
export async function DELETE(request: NextRequest,{params}:{params:Promise<{id:string}>}){const denied=requireServiceAccess(request,"directorates.manage");if(denied)return denied;const session=getRequestSession(request);if(!session)return NextResponse.json({error:"Authenticated session required."},{status:401});try{const{id}=await params;const[before]=await database().select().from(directorates).where(eq(directorates.id,id)).limit(1);if(!before)return NextResponse.json({error:"Directorate not found."},{status:404});await database().delete(directorates).where(eq(directorates.id,id));await recordAuditEvent({actorUserId:session.userId,action:"DIRECTORATE_DELETED",entityType:"directorate",entityId:id,beforeValue:before});return NextResponse.json({ok:true});}catch(error){return apiError(error);}}
