import { z } from "zod";

export const programmeInput = z.object({ code:z.string().trim().min(2).max(32), name:z.string().trim().min(3).max(160), objective:z.string().trim().min(10).max(2000) });
export const projectInput = z.object({ programmeId:z.uuid(), code:z.string().trim().min(2).max(32), name:z.string().trim().min(3).max(180), objective:z.string().trim().min(10).max(2000), startDate:z.string().date().optional(), endDate:z.string().date().optional() }).refine((data) => !data.startDate || !data.endDate || data.startDate <= data.endDate, { message:"Project end date must be after its start date.", path:["endDate"] });
export const activityInput = z.object({ projectId:z.uuid(), title:z.string().trim().min(3).max(180), description:z.string().trim().max(3000).optional(), dueDate:z.string().date().optional() });
export const reportInput = z.object({ projectId:z.uuid(), periodStart:z.string().date(), periodEnd:z.string().date(), narrative:z.string().trim().min(20).max(10000) }).refine((data) => data.periodStart <= data.periodEnd, { message:"Report end date must be after its start date.", path:["periodEnd"] });
export const activityRejectionInput = z.object({ reason:z.string().trim().min(10).max(2000) });
export const directorateInput = z.object({ code:z.string().trim().min(2).max(32), name:z.string().trim().min(3).max(160), description:z.string().trim().max(2000).optional() });
const geographyCode = z.string().trim().min(2).max(64).regex(/^[A-Za-z0-9_-]+$/, "Invalid geography code.");
export const geographyRef = z.union([z.uuid(), geographyCode]);
export const provinceInput = z.object({ code:z.string().trim().min(2).max(32).regex(/^[A-Za-z0-9_-]+$/, "Invalid province code."), name:z.string().trim().min(2).max(120) });
export const districtInput = z.object({ provinceId:geographyRef, code:z.string().trim().min(2).max(32).regex(/^[A-Za-z0-9_-]+$/, "Invalid district code."), name:z.string().trim().min(2).max(120) });
export const deliverySiteInput = z.object({ districtId:geographyRef, type:z.enum(["SCHOOL","INSTITUTION","COMMUNITY"]), name:z.string().trim().min(2).max(180), code:z.string().trim().max(64).regex(/^[A-Za-z0-9_-]+$/, "Invalid delivery site code.").optional() });
export const beneficiaryInput = z.object({ beneficiaryCode:z.string().trim().min(2).max(64), fullName:z.string().trim().min(2).max(240), dateOfBirth:z.string().date().optional(), ageGroup:z.enum(["CHILD","YOUTH","ADULT"]), sex:z.enum(["FEMALE","MALE","NOT_STATED"]).optional(), pwd:z.boolean().optional(), provinceId:geographyRef.optional(), districtId:geographyRef.optional(), deliverySiteId:geographyRef.optional() });
export const interventionInput = z.object({ projectId:z.uuid(), activityId:z.uuid().optional(), districtId:geographyRef, deliverySiteId:geographyRef.optional(), interventionDate:z.string().date(), title:z.string().trim().min(3).max(180), status:z.enum(["PLANNED","IN_PROGRESS","COMPLETE","CANCELLED"]).optional(), notes:z.string().trim().max(5000).optional() });
export const indicatorInput = z.object({ projectId:z.uuid(), activityId:z.uuid().optional(), code:z.string().trim().min(2).max(64), name:z.string().trim().min(3).max(240), description:z.string().trim().max(5000).optional(), level:z.enum(["OUTPUT","OUTCOME"]), unit:z.enum(["COUNT","PERCENTAGE","RATE","OTHER"]) });
export const targetInput = z.object({ indicatorId:z.uuid(), year:z.coerce.number().int().min(2000).max(2100), targetValue:z.coerce.number().finite(), provinceId:geographyRef.optional(), districtId:geographyRef.optional(), notes:z.string().trim().max(5000).optional() });
export const resultInput = z.object({ targetId:z.uuid(), periodStart:z.string().date(), periodEnd:z.string().date(), actualValue:z.coerce.number().finite(), notes:z.string().trim().max(5000).optional() }).refine((data)=>data.periodStart<=data.periodEnd,{message:"Result end date must be after its start date.",path:["periodEnd"]});
