import { eq } from "drizzle-orm";
import { z } from "zod";
import { NextRequest, NextResponse } from "next/server";
import { volunteerAssignments } from "@/db/schema";
import { database } from "@/lib/db";
import { apiError, requireServiceAccess } from "@/lib/api";
const input=z.object({role:z.string().trim().min(2).max(120),startDate:z.string().date(),endDate:z.string().date().optional().or(z.literal("")),status:z.enum(["PLANNED","ACTIVE","COMPLETED","CANCELLED"]),notes:z.string().trim().max(4000).optional()});
export async function PATCH(request:NextRequest){const denied=requireServiceAccess(request,"assignments.manage");if(denied)return denied;const id=request.nextUrl.searchParams.get("id");if(!id)return NextResponse.json({error:"Assignment id is required."},{status:400});const parsed=input.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Invalid assignment update",details:parsed.error.flatten()},{status:422});try{const[updated]=await database().update(volunteerAssignments).set({...parsed.data,updatedAt:new Date()}).where(eq(volunteerAssignments.id,id)).returning();if(!updated)return NextResponse.json({error:"Assignment not found."},{status:404});return NextResponse.json(updated);}catch(error){return apiError(error);}}
export async function DELETE(request:NextRequest){const denied=requireServiceAccess(request,"assignments.manage");if(denied)return denied;const id=request.nextUrl.searchParams.get("id");if(!id)return NextResponse.json({error:"Assignment id is required."},{status:400});try{const[existing]=await database().select({id:volunteerAssignments.id,status:volunteerAssignments.status}).from(volunteerAssignments).where(eq(volunteerAssignments.id,id)).limit(1);if(!existing)return NextResponse.json({error:"Assignment not found."},{status:404});if(existing.status==="ACTIVE")return NextResponse.json({error:"Active assignments cannot be deleted. Complete or cancel the assignment instead."},{status:422});await database().delete(volunteerAssignments).where(eq(volunteerAssignments.id,id));return NextResponse.json({ok:true});}catch(error){return apiError(error);}}
