"use client";

import { useEffect, useMemo, useState } from "react";
import ManagementSignalSync from "@/components/finance/management-signal-sync";

type Row = { code: string; name: string; directorateCode?: string | null; programmeCode?: string | null; budgetZmw: number; committedZmw: number; spentZmw: number; remainingZmw: number; utilisationPercent: number };
type Attention = { severity: "CRITICAL" | "HIGH" | "MEDIUM"; type: string; scope: string; code: string; name: string; message: string; recommendation: string; decision: string };
type ProjectPerformance = { projectId: string; projectCode: string; projectName: string; target: number; actual: number; indicators: number; achievedIndicators: number; achievementPercent: number; gap: number };
type PerformanceAttention = { severity: "HIGH" | "MEDIUM"; projectCode: string; projectName: string; message: string; recommendation: string; decision: string };
type FinanceData = {
  financialYear: number; budgetApprovedZmw: number; expenditureZmw: number; committedZmw: number; remainingZmw: number; uncommittedZmw: number; utilisationPercent: number; committedPercent: number;
  allocationSummary: { directorateBudgetZmw: number; programmeAllocationZmw: number; projectAllocationZmw: number; activityAllocationZmw: number };
  attention: Attention[]; attentionSummary: { critical: number; high: number; medium: number };
  directorates: Row[]; programmes: Row[]; projects: Array<Row & { projectCode: string; projectName: string; programmeCode: string | null; directorateCode: string | null }>; categories: Array<{ category: string; spentZmw: number }>;
};
type PerformanceData = { financialYear: number; basis: string; projectPerformance: ProjectPerformance[]; indicatorPerformance: Array<ProjectPerformance & { code: string; name: string; unit: string; level: string; activityTitle: string | null }>; attention: PerformanceAttention[] };

const money = (value: number) => new Intl.NumberFormat("en-ZM", { style: "currency", currency: "ZMW", maximumFractionDigits: 2 }).format(value);
const yearNow = new Date().getUTCFullYear();

export default function FinancialIntelligencePage() {
  const [year, setYear] = useState(yearNow);
  const [data, setData] = useState<FinanceData | null>(null);
  const [performance, setPerformance] = useState<PerformanceData | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    setData(null); setPerformance(null); setError("");
    Promise.all([
      fetch(`/api/finance/dashboard?year=${year}`, { cache: "no-store" }),
      fetch(`/api/finance/performance?year=${year}`, { cache: "no-store" }),
    ]).then(async ([financeResponse, performanceResponse]) => {
      if (!financeResponse.ok || !performanceResponse.ok) throw new Error("Unable to load financial and delivery intelligence.");
      return Promise.all([financeResponse.json(), performanceResponse.json()]);
    }).then(([finance, delivery]) => { setData(finance); setPerformance(delivery); }).catch((reason: Error) => setError(reason.message));
  }, [year]);

  const largestCategory = useMemo(() => data?.categories[0]?.category ?? "—", [data]);
  const severityLabel = (severity: Attention["severity"]) => severity === "CRITICAL" ? "Critical" : severity === "HIGH" ? "High" : "Review";
  const projectFinancial = useMemo(() => new Map((data?.projects ?? []).map((row) => [row.projectCode, row])), [data]);

  return (
    <main className="ims-shell">
      <aside className="sidebar"><div className="sidebar-brand"><div className="brand-mark">VSI</div><div><strong>VSI IMS</strong><span>Information Management</span></div></div><div className="workspace-label">WORKSPACE</div><nav className="sidebar-nav" aria-label="Main navigation"><a className="sidebar-link" href="/dashboard"><span className="nav-icon">⌂</span><span>Dashboard</span></a><a className="sidebar-link" href="/dashboard/workflow#programmes"><span className="nav-icon">▣</span><span>Programmes</span></a><a className="sidebar-link" href="/dashboard/workflow#projects"><span className="nav-icon">◫</span><span>Projects</span></a><a className="sidebar-link" href="/dashboard/workflow#activities"><span className="nav-icon">✓</span><span>Activities</span></a><a className="sidebar-link" href="/dashboard/workflow#reports"><span className="nav-icon">▤</span><span>Reports</span></a><a className="sidebar-link active" href="/dashboard/finance"><span className="nav-icon">₭</span><span>Financial Intelligence</span></a></nav></aside>
      <section className="workspace"><header className="topbar"><div className="breadcrumb"><span>VSI IMS</span><i>/</i><strong>Financial Intelligence</strong></div><div className="top-actions"><span className="env-pill"><span /> Connected</span><div className="top-avatar">PA</div></div></header>
        <div className="page-content"><div className="title-bar"><div><p className="eyebrow">FINANCE</p><h1>Financial Intelligence</h1><p>Budget, commitment, expenditure, delivery performance and management decisions from the governed hierarchy.</p></div><div className="title-actions"><label className="db-status">Financial year<select value={year} onChange={(event) => setYear(Number(event.target.value))}><option value={yearNow - 1}>{yearNow - 1}</option><option value={yearNow}>{yearNow}</option><option value={yearNow + 1}>{yearNow + 1}</option></select></label></div></div>
          {error ? <section className="panel" style={{ marginTop: 18, color: "#8a2b2b", fontSize: 16 }}>{error}</section> : !data || !performance ? <section className="panel" style={{ marginTop: 18, fontSize: 16 }}>Loading financial and delivery intelligence…</section> : <>
            <section className="stats-grid" aria-label="Financial metrics"><article className="metric-card metric-navy"><div className="metric-top"><span>DIRECTORATE BUDGET</span><span className="metric-icon">₭</span></div><strong>{money(data.budgetApprovedZmw)}</strong><p>Approved top-level budget</p><small>Child allocations are not double-counted.</small></article><article className="metric-card metric-blue"><div className="metric-top"><span>COMMITTED</span><span className="metric-icon">↗</span></div><strong>{money(data.committedZmw)}</strong><p>Committed expenditure</p><small>{data.committedPercent}% of top-level budget</small></article><article className="metric-card metric-gold"><div className="metric-top"><span>PAID</span><span className="metric-icon">✓</span></div><strong>{money(data.expenditureZmw)}</strong><p>Actual paid expenditure</p><small>{data.utilisationPercent}% budget utilisation</small></article><article className="metric-card metric-light"><div className="metric-top"><span>AVAILABLE</span><span className="metric-icon">%</span></div><strong>{money(data.remainingZmw)}</strong><p>Budget remaining</p><small>{money(data.uncommittedZmw)} not yet committed</small></article></section>

            <section className="panel" style={{ marginTop: 18 }}><div className="panel-heading"><div><p className="eyebrow dark">FINANCIAL × DELIVERY</p><h2>Resource use against results</h2></div><span className="more">FY {performance.financialYear}</span></div><p style={{ margin: "0 0 16px", color: "var(--ink-muted)" }}>{performance.basis}</p><div className="activity-table">{performance.projectPerformance.length === 0 ? <div className="more">No targets and results are recorded for this year.</div> : performance.projectPerformance.map((row) => { const financial = projectFinancial.get(row.projectCode); const utilisation = financial?.utilisationPercent ?? 0; const efficiency = utilisation === 0 ? null : Number((row.achievementPercent / utilisation * 100).toFixed(1)); return <article className="activity-row" key={row.projectId}><div className={`activity-mark ${row.achievementPercent < 50 ? "navy" : "blue"}`}>↗</div><div className="activity-main"><strong>{row.projectCode} · {row.projectName}</strong><span>Delivery {row.achievementPercent}% · Target {row.target} · Actual {row.actual} · Gap {row.gap}</span><span>Financial use {utilisation}%{efficiency === null ? "" : ` · delivery/spend index ${efficiency}%`}</span></div><span className={`status ${row.achievementPercent < 50 ? "red" : row.achievementPercent < 80 ? "gold" : "blue"}`}>{row.achievementPercent}%</span><time>{financial ? money(financial.spentZmw) : "No spend"}</time></article>; })}</div></section>

            <section className="panel" style={{ marginTop: 18 }}><div className="panel-heading"><div><p className="eyebrow dark">DELIVERY ATTENTION</p><h2>What requires attention</h2></div><span className="more">{performance.attention.length} delivery signals</span></div>{performance.attention.length === 0 ? <div className="notice-list"><div><span className="notice-dot blue-dot" /><p><strong>No delivery attention signals</strong><small>All projects with recorded targets are at or above the review threshold.</small></p><b>OK</b></div></div> : <div className="notice-list">{performance.attention.slice(0, 12).map((item, index) => <div key={`${item.projectCode}-${index}`}><span className="notice-dot" /><p><strong>{item.severity === "HIGH" ? "High" : "Review"} · {item.projectCode} · {item.projectName}</strong><small>{item.message}</small><small><b>Recommendation:</b> {item.recommendation}</small><small><b>Decision:</b> {item.decision}</small></p><b>{item.severity}</b></div>)}</div>}</section>

            <section className="panel" style={{ marginTop: 18 }}><div className="panel-heading"><div><p className="eyebrow dark">FINANCIAL ATTENTION</p><h2>What requires financial action</h2></div><span className="more">{data.attentionSummary.critical} critical · {data.attentionSummary.high} high · {data.attentionSummary.medium} review</span></div>{data.attention.length === 0 ? <div className="notice-list"><div><span className="notice-dot blue-dot" /><p><strong>No financial attention signals</strong><small>No threshold-based financial exception was detected for FY {data.financialYear}.</small></p><b>OK</b></div></div> : <div className="notice-list">{data.attention.slice(0, 12).map((item, index) => <div key={`${item.scope}-${item.code}-${item.type}-${index}`}><span className="notice-dot" /><p><strong>{severityLabel(item.severity)} · {item.scope} · {item.code}</strong><small>{item.message}</small><small><b>Recommendation:</b> {item.recommendation}</small><small><b>Decision:</b> {item.decision}</small></p><b>{item.severity}</b></div>)}</div>}</section>

            <ManagementSignalSync year={year} financeProjects={data.projects} deliveryProjects={performance.projectPerformance} />

            <section className="panel" style={{ marginTop: 18 }}><div className="panel-heading"><div><p className="eyebrow dark">ALLOCATION CONTROL</p><h2>Budget flowing down the organisation</h2></div><span className="more">FY {data.financialYear}</span></div><div className="mini-metrics"><div><strong>{money(data.allocationSummary.directorateBudgetZmw)}</strong><span>Directorate budget</span></div><div><strong>{money(data.allocationSummary.programmeAllocationZmw)}</strong><span>Programme allocations</span></div><div><strong>{money(data.allocationSummary.projectAllocationZmw)}</strong><span>Project allocations</span></div><div><strong>{money(data.allocationSummary.activityAllocationZmw)}</strong><span>Activity allocations</span></div></div></section>

            <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow dark">DIRECTORATE POSITION</p><h2>Directorates</h2></div></div><div className="activity-table">{data.directorates.length === 0 ? <div className="more">No approved Directorate budgets for this year.</div> : data.directorates.map((row) => <article className="activity-row" key={row.code}><div className="activity-mark navy">₭</div><div className="activity-main"><strong>{row.code} · {row.name}</strong><span>Budget {money(row.budgetZmw)} · Committed {money(row.committedZmw)} · Paid {money(row.spentZmw)}</span></div><span className="status blue">{row.utilisationPercent}%</span><time>{money(row.remainingZmw)}</time></article>)}</div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow dark">PROGRAMME POSITION</p><h2>Programmes</h2></div></div><div className="activity-table">{data.programmes.length === 0 ? <div className="more">No approved Programme allocations for this year.</div> : data.programmes.map((row) => <article className="activity-row" key={row.code}><div className="activity-mark blue">₭</div><div className="activity-main"><strong>{row.code} · {row.name}</strong><span>{row.directorateCode ?? "Directorate"} · Budget {money(row.budgetZmw)} · Paid {money(row.spentZmw)}</span></div><span className="status blue">{row.utilisationPercent}%</span><time>{money(row.remainingZmw)}</time></article>)}</div></section></div>

            <section className="panel" style={{ marginTop: 18 }}><div className="panel-heading"><div><p className="eyebrow dark">PROJECT POSITION</p><h2>Projects</h2></div></div><div className="activity-table">{data.projects.length === 0 ? <div className="more">No approved Project budgets for this year.</div> : data.projects.map((row) => <article className="activity-row" key={row.projectCode}><div className="activity-mark blue">₭</div><div className="activity-main"><strong>{row.projectCode} · {row.projectName}</strong><span>{row.directorateCode ?? "Directorate"} · {row.programmeCode ?? "Programme"} · Budget {money(row.budgetZmw)} · Committed {money(row.committedZmw)} · Paid {money(row.spentZmw)}</span></div><span className="status blue">{row.utilisationPercent}%</span><time>{money(row.remainingZmw)}</time></article>)}</div></section>

            <div className="dashboard-grid" style={{ marginTop: 18 }}><section className="panel"><div className="panel-heading"><div><p className="eyebrow dark">EXPENDITURE MIX</p><h2>Paid expenditure by category</h2></div></div><div className="notice-list">{data.categories.length === 0 ? <div className="more">No paid expenditure recorded for this year.</div> : data.categories.map((category) => <div key={category.category}><span className="notice-dot blue-dot" /><p><strong>{category.category}</strong><small>{money(category.spentZmw)}</small></p><b>{data.expenditureZmw === 0 ? "0%" : `${Math.round((category.spentZmw / data.expenditureZmw) * 100)}%`}</b></div>)}</div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow dark">POSITION</p><h2>Management view</h2></div></div><div className="mini-metrics"><div><strong>{data.directorates.length}</strong><span>Directorates</span></div><div><strong>{data.programmes.length}</strong><span>Programmes funded</span></div><div><strong>{data.projects.length}</strong><span>Projects funded</span></div><div><strong>{largestCategory}</strong><span>Largest spend category</span></div></div><p style={{ marginTop: 18, color: "var(--ink-muted)" }}>Attention signals are decision support. They identify exceptions and recommended actions; authorised management makes the decision.</p></section></div>
          </>}
        </div>
      </section>
    </main>
  );
}
