import { boolean, check, date, integer, numeric, pgEnum, pgTable, text, timestamp, unique, uuid, varchar } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

const id = { id: uuid("id").defaultRandom().primaryKey(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };
export const directorates = pgTable("directorates", { ...id, code: varchar("code", { length: 32 }).notNull().unique(), name: varchar("name", { length: 160 }).notNull(), description: text("description"), active: boolean("active").default(true).notNull() });
export const projectStatus = pgEnum("project_status", ["DRAFT","ACTIVE","ON_HOLD","CLOSED"]);
export const activityStatus = pgEnum("activity_status", ["PLANNED","IN_PROGRESS","COMPLETE","CANCELLED"]);
export const activityApprovalStatus = pgEnum("activity_approval_status", ["DRAFT","SUBMITTED","APPROVED","REJECTED"]);
export const programmes = pgTable("programmes", { ...id, directorateId: uuid("directorate_id").references(() => directorates.id), code: varchar("code", { length: 32 }).notNull().unique(), name: varchar("name", { length: 160 }).notNull(), objective: text("objective").notNull(), active: boolean("active").default(true).notNull() });
export const projects = pgTable("projects", { ...id, programmeId: uuid("programme_id").references(() => programmes.id).notNull(), code: varchar("code", { length: 32 }).notNull().unique(), name: varchar("name", { length: 180 }).notNull(), objective: text("objective").notNull(), status: projectStatus("status").default("DRAFT").notNull(), startDate: date("start_date"), endDate: date("end_date") });
export const activities = pgTable("activities", { ...id, projectId: uuid("project_id").references(() => projects.id).notNull(), title: varchar("title", { length: 180 }).notNull(), description: text("description"), status: activityStatus("status").default("PLANNED").notNull(), approvalStatus: activityApprovalStatus("approval_status").default("DRAFT").notNull(), dueDate: date("due_date"), ownerUserId: uuid("owner_user_id"), submittedAt: timestamp("submitted_at", { withTimezone: true }), submittedByUserId: uuid("submitted_by_user_id"), approvedAt: timestamp("approved_at", { withTimezone: true }), approvedByUserId: uuid("approved_by_user_id"), rejectionReason: text("rejection_reason") });
export const reports = pgTable("reports", { ...id, projectId: uuid("project_id").references(() => projects.id).notNull(), periodStart: date("period_start").notNull(), periodEnd: date("period_end").notNull(), narrative: text("narrative").notNull(), submittedByUserId: uuid("submitted_by_user_id").notNull(), approvedAt: timestamp("approved_at", { withTimezone: true }) });
export const auditEvents = pgTable("audit_events", { ...id, actorUserId: uuid("actor_user_id").notNull(), action: varchar("action", { length: 80 }).notNull(), entityType: varchar("entity_type", { length: 80 }).notNull(), entityId: uuid("entity_id").notNull(), beforeValue: text("before_value"), afterValue: text("after_value") });
export const provinces = pgTable("provinces", { ...id, code: varchar("code", { length: 32 }).notNull().unique(), name: varchar("name", { length: 120 }).notNull().unique(), active: boolean("active").default(true).notNull() });
export const districts = pgTable("districts", { ...id, provinceId: uuid("province_id").references(() => provinces.id).notNull(), code: varchar("code", { length: 32 }).notNull().unique(), name: varchar("name", { length: 120 }).notNull(), active: boolean("active").default(true).notNull() });
export const deliverySiteType = pgEnum("delivery_site_type", ["SCHOOL","INSTITUTION","COMMUNITY"]);
export const deliverySites = pgTable("delivery_sites", { ...id, districtId: uuid("district_id").references(() => districts.id).notNull(), type: deliverySiteType("type").notNull(), name: varchar("name", { length: 180 }).notNull(), code: varchar("code", { length: 64 }), active: boolean("active").default(true).notNull() });
export const beneficiarySex = pgEnum("beneficiary_sex", ["FEMALE","MALE","NOT_STATED"]);
export const beneficiaryAgeGroup = pgEnum("beneficiary_age_group", ["CHILD","YOUTH","ADULT"]);
export const beneficiaries = pgTable("beneficiaries", { ...id, beneficiaryCode: varchar("beneficiary_code", { length: 64 }).notNull().unique(), fullName: varchar("full_name", { length: 240 }).notNull(), dateOfBirth: date("date_of_birth"), ageGroup: beneficiaryAgeGroup("age_group").notNull(), sex: beneficiarySex("sex").default("NOT_STATED").notNull(), pwd: boolean("pwd").default(false).notNull(), provinceId: uuid("province_id").references(() => provinces.id), districtId: uuid("district_id").references(() => districts.id), deliverySiteId: uuid("delivery_site_id").references(() => deliverySites.id), active: boolean("active").default(true).notNull() });
export const interventionStatus = pgEnum("intervention_status", ["PLANNED","IN_PROGRESS","COMPLETE","CANCELLED"]);
export const interventions = pgTable("interventions", { ...id, projectId: uuid("project_id").references(() => projects.id).notNull(), activityId: uuid("activity_id").references(() => activities.id), districtId: uuid("district_id").references(() => districts.id).notNull(), deliverySiteId: uuid("delivery_site_id").references(() => deliverySites.id), interventionDate: date("intervention_date").notNull(), title: varchar("title", { length: 180 }).notNull(), status: interventionStatus("status").default("PLANNED").notNull(), notes: text("notes") });
export const interventionParticipants = pgTable("intervention_participants", { ...id, interventionId: uuid("intervention_id").references(() => interventions.id).notNull(), beneficiaryId: uuid("beneficiary_id").references(() => beneficiaries.id).notNull() }, (table) => [unique("intervention_participants_intervention_beneficiary_unique").on(table.interventionId, table.beneficiaryId)]);
export const indicatorLevel = pgEnum("indicator_level", ["OUTPUT","OUTCOME"]);
export const indicatorUnit = pgEnum("indicator_unit", ["COUNT","PERCENTAGE","RATE","OTHER"]);
export const indicators = pgTable("indicators", { ...id, projectId: uuid("project_id").references(() => projects.id).notNull(), activityId: uuid("activity_id").references(() => activities.id), code: varchar("code", { length: 64 }).notNull().unique(), name: varchar("name", { length: 240 }).notNull(), description: text("description"), level: indicatorLevel("level").notNull(), unit: indicatorUnit("unit").notNull(), active: boolean("active").default(true).notNull() });
export const targets = pgTable("targets", { ...id, indicatorId: uuid("indicator_id").references(() => indicators.id).notNull(), year: integer("year").notNull(), targetValue: numeric("target_value", { precision: 14, scale: 2 }).notNull(), provinceId: uuid("province_id").references(() => provinces.id), districtId: uuid("district_id").references(() => districts.id), notes: text("notes") }, (table) => [unique("targets_indicator_year_province_district_unique").on(table.indicatorId, table.year, table.provinceId, table.districtId)]);
export const results = pgTable("results", { ...id, targetId: uuid("target_id").references(() => targets.id).notNull(), periodStart: date("period_start").notNull(), periodEnd: date("period_end").notNull(), actualValue: numeric("actual_value", { precision: 14, scale: 2 }).notNull(), notes: text("notes") }, (table) => [unique("results_target_period_unique").on(table.targetId, table.periodStart, table.periodEnd)]);
export const financeBudgetStatus = pgEnum("finance_budget_status", ["DRAFT","APPROVED","CLOSED"]);
export const financeBudgetLevel = pgEnum("finance_budget_level", ["DIRECTORATE","PROGRAMME","PROJECT","ACTIVITY"]);
export const financeExpenseStatus = pgEnum("finance_expense_status", ["DRAFT","SUBMITTED","APPROVED","REJECTED","PAID"]);
export const financeBudgets = pgTable("finance_budgets", { ...id, financialYear: integer("financial_year").notNull(), budgetCode: varchar("budget_code", { length: 64 }).notNull().unique(), level: financeBudgetLevel("level").default("PROJECT").notNull(), directorateId: uuid("directorate_id").references(() => directorates.id), programmeId: uuid("programme_id").references(() => programmes.id), projectId: uuid("project_id").references(() => projects.id), activityId: uuid("activity_id").references(() => activities.id), parentBudgetId: uuid("parent_budget_id"), amountZmw: numeric("amount_zmw", { precision: 16, scale: 2 }).notNull(), status: financeBudgetStatus("status").default("DRAFT").notNull(), createdByUserId: uuid("created_by_user_id").notNull(), notes: text("notes") }, (table) => [unique("finance_budget_project_year_unique").on(table.projectId, table.financialYear), check("finance_budget_scope_check", sql`((level = 'DIRECTORATE' AND directorate_id IS NOT NULL AND programme_id IS NULL AND project_id IS NULL AND activity_id IS NULL) OR (level = 'PROGRAMME' AND directorate_id IS NULL AND programme_id IS NOT NULL AND project_id IS NULL AND activity_id IS NULL) OR (level = 'PROJECT' AND directorate_id IS NULL AND programme_id IS NULL AND project_id IS NOT NULL AND activity_id IS NULL) OR (level = 'ACTIVITY' AND directorate_id IS NULL AND programme_id IS NULL AND project_id IS NULL AND activity_id IS NOT NULL))`) ]);
export const financeExpenses = pgTable("finance_expenses", { ...id, budgetId: uuid("budget_id").references(() => financeBudgets.id).notNull(), expenseDate: date("expense_date").notNull(), description: varchar("description", { length: 240 }).notNull(), category: varchar("category", { length: 80 }).notNull(), amountZmw: numeric("amount_zmw", { precision: 16, scale: 2 }).notNull(), status: financeExpenseStatus("status").default("DRAFT").notNull(), submittedByUserId: uuid("submitted_by_user_id"), approvedByUserId: uuid("approved_by_user_id"), approvedAt: timestamp("approved_at", { withTimezone: true }), notes: text("notes") });
export const managementActionStatus = pgEnum("management_action_status", ["OPEN","IN_PROGRESS","COMPLETED","CANCELLED"]);
export const managementActions = pgTable("management_actions", { ...id, entityType: varchar("entity_type", { length: 80 }).notNull(), entityId: uuid("entity_id").notNull(), source: varchar("source", { length: 80 }).notNull(), severity: varchar("severity", { length: 20 }).notNull(), finding: text("finding").notNull(), recommendation: text("recommendation").notNull(), decision: text("decision"), decisionByUserId: uuid("decision_by_user_id"), decisionAt: timestamp("decision_at", { withTimezone: true }), actionOwnerUserId: uuid("action_owner_user_id"), dueDate: date("due_date"), status: managementActionStatus("status").default("OPEN").notNull(), resolution: text("resolution") });

export const volunteerStatus = pgEnum("volunteer_status", ["APPLICANT","ACTIVE","INACTIVE","ALUMNI"]);
export const volunteerAssignmentStatus = pgEnum("volunteer_assignment_status", ["PLANNED","ACTIVE","COMPLETED","CANCELLED"]);
export const volunteers = pgTable("volunteers", { ...id, volunteerCode: varchar("volunteer_code", { length: 64 }).notNull().unique(), fullName: varchar("full_name", { length: 240 }).notNull(), email: varchar("email", { length: 240 }), phone: varchar("phone", { length: 40 }), dateOfBirth: date("date_of_birth"), sex: beneficiarySex("sex").default("NOT_STATED").notNull(), provinceId: uuid("province_id").references(() => provinces.id), districtId: uuid("district_id").references(() => districts.id), status: volunteerStatus("status").default("APPLICANT").notNull(), joinedAt: date("joined_at"), notes: text("notes") });
export const volunteerSkills = pgTable("volunteer_skills", { ...id, volunteerId: uuid("volunteer_id").references(() => volunteers.id).notNull(), skill: varchar("skill", { length: 120 }).notNull(), proficiency: varchar("proficiency", { length: 40 }), verified: boolean("verified").default(false).notNull() }, (table) => [unique("volunteer_skill_unique").on(table.volunteerId, table.skill)]);
export const volunteerTraining = pgTable("volunteer_training", { ...id, volunteerId: uuid("volunteer_id").references(() => volunteers.id).notNull(), title: varchar("title", { length: 180 }).notNull(), trainingDate: date("training_date").notNull(), provider: varchar("provider", { length: 180 }), certificateReference: varchar("certificate_reference", { length: 120 }), completed: boolean("completed").default(true).notNull() });
export const volunteerAssignments = pgTable("volunteer_assignments", { ...id, volunteerId: uuid("volunteer_id").references(() => volunteers.id).notNull(), projectId: uuid("project_id").references(() => projects.id).notNull(), activityId: uuid("activity_id").references(() => activities.id), districtId: uuid("district_id").references(() => districts.id), deliverySiteId: uuid("delivery_site_id").references(() => deliverySites.id), role: varchar("role", { length: 120 }).notNull(), startDate: date("start_date").notNull(), endDate: date("end_date"), status: volunteerAssignmentStatus("status").default("PLANNED").notNull(), notes: text("notes") });
export const volunteerParticipation = pgTable("volunteer_participation", { ...id, volunteerId: uuid("volunteer_id").references(() => volunteers.id).notNull(), activityId: uuid("activity_id").references(() => activities.id).notNull(), participationDate: date("participation_date").notNull(), hours: numeric("hours", { precision: 8, scale: 2 }).notNull(), notes: text("notes") }, (table) => [unique("volunteer_participation_unique").on(table.volunteerId, table.activityId, table.participationDate)]);
export const volunteerRecognition = pgTable("volunteer_recognition", { ...id, volunteerId: uuid("volunteer_id").references(() => volunteers.id).notNull(), recognitionDate: date("recognition_date").notNull(), title: varchar("title", { length: 180 }).notNull(), description: text("description") });

// Other vertical slices own their authoritative data and reference projects rather than duplicate project data.