import { boolean, date, pgEnum, pgTable, text, timestamp, uuid, varchar } from "drizzle-orm/pg-core";
const id = { id: uuid("id").defaultRandom().primaryKey(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };
export const projectStatus = pgEnum("project_status", ["DRAFT","ACTIVE","ON_HOLD","CLOSED"]);
export const activityStatus = pgEnum("activity_status", ["PLANNED","IN_PROGRESS","COMPLETE","CANCELLED"]);
export const programmes = pgTable("programmes", { ...id, code: varchar("code", { length: 32 }).notNull().unique(), name: varchar("name", { length: 160 }).notNull(), objective: text("objective").notNull(), active: boolean("active").default(true).notNull() });
export const projects = pgTable("projects", { ...id, programmeId: uuid("programme_id").references(() => programmes.id).notNull(), code: varchar("code", { length: 32 }).notNull().unique(), name: varchar("name", { length: 180 }).notNull(), objective: text("objective").notNull(), status: projectStatus("status").default("DRAFT").notNull(), startDate: date("start_date"), endDate: date("end_date") });
export const activities = pgTable("activities", { ...id, projectId: uuid("project_id").references(() => projects.id).notNull(), title: varchar("title", { length: 180 }).notNull(), description: text("description"), status: activityStatus("status").default("PLANNED").notNull(), dueDate: date("due_date"), ownerUserId: uuid("owner_user_id") });
export const reports = pgTable("reports", { ...id, projectId: uuid("project_id").references(() => projects.id).notNull(), periodStart: date("period_start").notNull(), periodEnd: date("period_end").notNull(), narrative: text("narrative").notNull(), submittedByUserId: uuid("submitted_by_user_id").notNull(), approvedAt: timestamp("approved_at", { withTimezone: true }) });
export const auditEvents = pgTable("audit_events", { ...id, actorUserId: uuid("actor_user_id").notNull(), action: varchar("action", { length: 80 }).notNull(), entityType: varchar("entity_type", { length: 80 }).notNull(), entityId: uuid("entity_id").notNull(), beforeValue: text("before_value"), afterValue: text("after_value") });
// Other vertical slices own their authoritative data and reference projects rather than duplicate project data.
